;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Mission.Event.Door.KeycardAccepted",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Examine.Telephone.Completed",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Item.DataChip.Acquired",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Item.Keycard.Acquired",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Item.Pistol.Acquired",DevComment="")
+GameplayTagList=(Tag="Mission.Event.Stealth.Detected",DevComment="")
+GameplayTagList=(Tag="Mission.Target.Exit",DevComment="")
+GameplayTagList=(Tag="Mission.Target.Keycard",DevComment="")
+GameplayTagList=(Tag="Mission.Target.Pistol",DevComment="")
+GameplayTagList=(Tag="Mission.Target.SecurityDoor",DevComment="")
+GameplayTagList=(Tag="Mission.Target.Telephone",DevComment="")

